export const AUTH_SIGNIN_START = 'AUTH_SIGNIN_START'
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS'
export const AUTH_SIGNIN_ERROR = 'AUTH_SIGNIN_ERROR'
export const AUTH_SIGNOUT = 'AUTH_SIGNOUT'

export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_OAUTH_SUCCESS'
export const GOOGLE_AUTH_ERROR = 'GOOGLE_OAUTH_ERROR'
export const GOOGLE_SIGNOUT = 'GOOGLE_SIGNOUT'

export const AUTH_SIGNUP_START = 'AUTH_SIGNUP_START'
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS'
export const AUTH_SIGNUP_ERROR = 'AUTH_SIGNUP_ERROR'

export const ACCOUNT_INFO_START = 'ACCOUNT_INFO_START'
export const ACCOUNT_INFO_SUCCESS = 'ACCOUNT_INFO_SUCCESS'
export const ACCOUNT_INFO_ERROR = 'ACCOUNT_INFO_ERROR'

export const UPDATE_ACCOUNT_START = 'UPDATE_ACCOUNT_START'
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS'
export const UPDATE_ACCOUNT_ERROR = 'UPDATE_ACCOUNT_ERROR'
export const UPDATE_ACCOUNT_RESTART = 'UPDATE_ACCOUNT_RESTART'
