export const AUTH_SIGNIN_START = 'AUTH_SIGNIN_START'
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS'
export const AUTH_SIGNIN_ERROR = 'AUTH_SIGNIN_ERROR'
export const AUTH_SIGNOUT = 'AUTH_SIGNOUT'
