// PRODUCT CONSTANTS

//DELETE A PRODUCT
export const MANAGER_DELETE_PRODUCT_START = 'MANAGER_DELETE_PRODUCT_START'
export const MANAGER_DELETE_PRODUCT = 'MANAGER_DELETE_PRODUCT'
export const MANAGER_DELETE_PRODUCT_ERROR = 'MANAGER_DELETE_PRODUCT_ERROR'

//CREATE A PRODUCT
export const MANAGER_NEW_PRODUCT_START = 'MANAGER_NEW_PRODUCT_START'
export const MANAGER_NEW_PRODUCT = 'MANAGER_NEW_PRODUCT'
export const MANAGER_NEW_PRODUCT_ERROR = 'MANAGER_NEW_PRODUCT_ERROR'
export const MANAGER_NEW_PRODUCT_RESTART = 'MANAGER_NEW_PRODUCT_RESTART'

//UPDATE A PRODUCT
export const MANAGER_UPDATE_PRODUCT_START = 'MANAGER_UPDATE_PRODUCT_START'
export const MANAGER_UPDATE_PRODUCT = 'MANAGER_UPDATE_PRODUCT'
export const MANAGER_UPDATE_PRODUCT_ERROR = 'MANAGER_UPDATE_PRODUCT_ERROR'
export const MANAGER_UPDATE_PRODUCT_RESTART = 'MANAGER_UPDATE_PRODUCT_RESTART'

// GET ALL ORDERS
export const GET_ALL_ORDERS_MANAGER_START = 'GET_ALL_ORDERS_MANAGER_START'
export const GET_ALL_ORDERS_MANAGER = 'GET_ALL_ORDERS_MANAGER'
export const GET_ALL_ORDERS_MANAGER_ERROR = 'GET_ALL_ORDERS_MANAGER_ERROR'

// MARK ORDERS AS CONFIRMED/ACCEPTED
export const CONFIRM_ORDER_MANAGER_START = 'CONFIRM_ORDER_MANAGER_START'
export const CONFIRM_ORDER_MANAGER = 'CONFIRM_ORDER_MANAGER'
export const CONFIRM_ORDER_MANAGER_ERROR = 'CONFIRM_ORDER_MANAGER_ERROR'
export const CONFIRM_ORDER_MANAGER_RESTART = 'CONFIRM_ORDER_MANAGER_RESTART'

// MARK ORDERS AS DISPATCHED
export const DISPATCH_ORDER_MANAGER_START = 'DISPATCH_ORDER_MANAGER_START'
export const DISPATCH_ORDER_MANAGER = 'DISPATCH_ORDER_MANAGER'
export const DISPATCH_ORDER_MANAGER_ERROR = 'DISPATCH_ORDER_MANAGER_ERROR'
export const DISPATCH_ORDER_MANAGER_RESTART = 'DISPATCH_ORDER_MANAGER_RESTART'

// MARK ORDERS AS DELIVERED
export const DELIVER_ORDER_MANAGER_START = 'DELIVER_ORDER_MANAGER_START'
export const DELIVER_ORDER_MANAGER = 'DELIVER_ORDER_MANAGER'
export const DELIVER_ORDER_MANAGER_ERROR = 'DELIVER_ORDER_MANAGER_ERROR'
export const DELIVER_ORDER_MANAGER_RESTART = 'DELIVER_ORDER_MANAGER_RESTART'
