// PRODUCT CONSTANTS

//DELETE A PRODUCT
export const MANAGER_DELETE_PRODUCT_START = 'MANAGER_DELETE_PRODUCT_START'
export const MANAGER_DELETE_PRODUCT = 'MANAGER_DELETE_PRODUCT'
export const MANAGER_DELETE_PRODUCT_ERROR = 'MANAGER_DELETE_PRODUCT_ERROR'

//CREATE A PRODUCT
export const MANAGER_NEW_PRODUCT_START = 'MANAGER_NEW_PRODUCT_START'
export const MANAGER_NEW_PRODUCT = 'MANAGER_NEW_PRODUCT'
export const MANAGER_NEW_PRODUCT_ERROR = 'MANAGER_NEW_PRODUCT_ERROR'
export const MANAGER_NEW_PRODUCT_RESTART = 'MANAGER_NEW_PRODUCT_RESTART'

//UPDATE A PRODUCT
export const MANAGER_UPDATE_PRODUCT_START = 'MANAGER_UPDATE_PRODUCT_START'
export const MANAGER_UPDATE_PRODUCT = 'MANAGER_UPDATE_PRODUCT'
export const MANAGER_UPDATE_PRODUCT_ERROR = 'MANAGER_UPDATE_PRODUCT_ERROR'
export const MANAGER_UPDATE_PRODUCT_RESTART = 'MANAGER_UPDATE_PRODUCT_RESTART'

// GET ALL ORDERS
export const GET_ALL_ORDERS_MANAGER_START = 'GET_ALL_ORDERS_MANAGER_START'
export const GET_ALL_ORDERS_MANAGER = 'GET_ALL_ORDERS_MANAGER'
export const GET_ALL_ORDERS_MANAGER_ERROR = 'GET_ALL_ORDERS_MANAGER_ERROR'
