// PRODUCT CONSTANTS

//DELETE A PRODUCT
export const MANAGER_DELETE_PRODUCT_START = 'MANAGER_DELETE_PRODUCT_START'
export const MANAGER_DELETE_PRODUCT = 'MANAGER_DELETE_PRODUCT'
export const MANAGER_DELETE_PRODUCT_ERROR = 'MANAGER_DELETE_PRODUCT_ERROR'
