export const CREATE_ORDER = 'CREATE_ORDER'
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR'
export const CREATE_ORDER_START = 'CREATE_ORDER_START'

// GET ORDER DETAILS
export const GET_ORDER = 'GET_ORDER'
export const GET_ORDER_ERROR = 'GET_ORDER_ERROR'
export const GET_ORDER_START = 'GET_ORDER_START'

//PAY ORDER
export const PAY_ORDER = 'PAY_ORDER'
export const PAY_ORDER_ERROR = 'PAY_ORDER_ERROR'
export const PAY_ORDER_START = 'PAY_ORDER_START'
export const PAY_RESET = 'PAY_RESET'

//GET USER ORDERS
export const GET_USER_ORDERS = 'GET_USER_ORDERS'
export const GET_USER_ORDERS_ERROR = 'GET_USER_ORDERS_ERROR'
export const GET_USER_ORDERS_START = 'GET_USER_ORDERS_START'
