export const CREATE_ORDER = 'CREATE_ORDER'
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR'
// export const CREATE_ORDER_START = 'CREATE_ORDER_START'

// GET ORDER DETAILS
export const GET_ORDER = 'GET_ORDER'
export const GET_ORDER_ERROR = 'GET_ORDER_ERROR'
