// FETCH_ALL PRODUCTS
export const FETCH_ALL_REQUEST = 'FETCH_ALL_REQUEST'
export const FETCH_ALL_SUCCESS = 'FETCH_ALL_SUCCESS'
export const FETCH_ALL_ERROR = 'FETCH_ALL_ERROR'

// FETCH_PRODUCT
export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR'

// RATE PRODUCT
export const RATE_PRODUCT_REQUEST = 'RATE_PRODUCT_REQUEST'
export const RATE_PRODUCT_SUCCESS = 'RATE_PRODUCT_SUCCESS'
export const RATE_PRODUCT_ERROR = 'RATE_PRODUCT_ERROR'
export const RATE_PRODUCT_RESTART = 'RATE_PRODUCT_RESTART'
