// FETCH_ALL RECIPES
export const FETCH_ALL_RECIPES_START = 'FETCH_ALL_RECIPES_START'
export const FETCH_ALL_RECIPES_SUCCESS = 'FETCH_ALL_RECIPES_SUCCESS'
export const FETCH_ALL_RECIPES_ERROR = 'FETCH_ALL_RECIPES_ERROR'

// FETCH_RECIPE
export const FETCH_RECIPE_START = 'FETCH_RECIPE_START'
export const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS'
export const FETCH_RECIPE_ERROR = 'FETCH_RECIPE_ERROR'

//GET USER RECIPES
export const GET_USER_RECIPES = 'GET_USER_RECIPES'
export const GET_USER_RECIPES_ERROR = 'GET_USER_RECIPES_ERROR'
export const GET_USER_RECIPES_START = 'GET_USER_RECIPES_START'
export const GET_USER_RECIPES_CLEAR = 'GET_USER_RECIPES_CLEAR'

// LIKE_RECIPE
export const LIKE_RECIPE_START = 'LIKE_RECIPE_START'
export const LIKE_RECIPE_SUCCESS = 'LIKE_RECIPE_SUCCESS'
export const LIKE_RECIPE_ERROR = 'LIKE_RECIPE_ERROR'
export const LIKE_RECIPE_RESTART = 'LIKE_RECIPE_RESTART'

//CREATE A RECIPE
export const CREATE_RECIPE_START = 'CREATE_RECIPE_START'
export const CREATE_RECIPE = 'CREATE_RECIPE'
export const CREATE_RECIPE_ERROR = 'CREATE_RECIPE_ERROR'
export const CREATE_RECIPE_RESTART = 'CREATE_RECIPE_RESTART'

//UPDATE A PRECIPE
export const UPDATE_RECIPE_START = 'UPDATE_RECIPE_START'
export const UPDATE_RECIPE = 'UPDATE_RECIPE'
export const UPDATE_RECIPE_ERROR = 'UPDATE_RECIPE_ERROR'
export const UPDATE_RECIPE_RESTART = 'UPDATE_RECIPE_RESTART'

//DELETE A RECIPE
export const DELETE_RECIPE_START = 'DELETE_RECIPE_START'
export const DELETE_RECIPE = 'DELETE_RECIPE'
export const DELETE_RECIPE_ERROR = 'DELETE_RECIPE_ERROR'
